SPQR's changes from Dili

diff --git a/P5/Roma b/P5/Roma
--- a/P5/Roma
+++ b/P5/Roma
@@ -1,55 +1,52 @@
-#!/bin/bash
+#!/bin/bash 
+#
+# Roma: transform TEI ODD files to schema and documentation
+#
+# Sebastian Rahtz, April 2005
+# copyright: TEI Consortium
+# license: GPL
 
 makeRelax()
 {
     echo "1. make Relax NG from ODD"
-    xsltproc --stringparam TEISERVER $TEISERVER  \
-             --stringparam verbose true          \
+    xsltproc -o $N.compiled.odd \
+    --stringparam TEISERVER $TEISERVER  \
+    $TEIDIR/p5/odds/odd2odd.xsl $ODD 
+    xsltproc  \
+             --stringparam Method byvalue         \
              --stringparam RNGDIR $RESULTS       \
-             --stringparam schemaBaseURL $S/ $TEIDIR/base/p5/odds/odd2relax.xsl $ODD
+             $TEIDIR/p5/odds/odd2relax.xsl $N.compiled.odd
     cd $RESULTS
     xmllint --format $N.rng > $$.xml; mv $$.xml $N.rng
     echo "2. make Relax NG compact from XML"
     trang $N.rng $N.rnc  || die " trang fails"
-    echo "3. expand includes in Relax NG"
-    xsltproc -o $N.compiled.rng $TEIDIR/base/p5/odds/expandincludes.xsl $N.rng 
-    echo "4. convert expanded form to compact syntax"
-    trang $N.compiled.rng $N.compiled.rnc  || die " trang fails"
+    $doc && makeDOC
+    $debug || rm  $N.compiled.odd
+}
+
+makeXSD()
+{
+    echo "3. make XSD from Relax NG and then mangle XSD"
+    trang  -o disable-abstract-elements $N.rng $N.xsd || die " trang fails"
+#    xsltproc -o $N.xsd $TEIDIR/p5/odds/manglexsd.xsl $N.temp.xsd
+#    $debug || rm $N.temp.xsd
+#    $debug || rm $N.temp1.rng  
+    test -f xml.xsd && perl -p -i -e 's/<xs:import.*//' xml.xsd
 }
 
 makeDTD()
 {
-    echo "6. simplify schema before attempting DTD conversion"
-    xsltproc   $TEIDIR/base/p5/odds/nomorechoice.xsl $N.compiled.rng \
-    | xsltproc $TEIDIR/base/p5/odds/simplifyfordtd.xsl -             \
-    | xsltproc $TEIDIR/base/p5/odds/simplifyfordtd.xsl -             \
-    | xsltproc $TEIDIR/base/p5/odds/simplifyfordtd.xsl -             \
-    | xsltproc $TEIDIR/base/p5/odds/simplifyfordtd.xsl -             \
-    | xsltproc -o $N.temp2.rng $TEIDIR/base/p5/odds/simplifyfordtd.xsl - 
-    echo "7. convert simplified form to DTD"
-    trang $N.temp2.rng $N.dtd || die " trang fails"
-    $debug || rm $N.temp2.rng 
-    perl -p -i -e 's/ns1://;s/xmlns:ns1/xmlns/' $N.dtd
+    echo "4. make DTD from Relax NG"
+    trang $N.rng $N.dtd || die " trang fails"
+    perl -p -i -e 's/ns1://;s/xmlns:ns1/xmlns/;s/xml:id CDATA/xml:id ID/' $N.dtd
 
 }
 
 makeDOC() 
 {
-    echo "8. make expanded documented ODD"
-    xsltproc --stringparam TEISERVER $TEISERVER $TEIDIR/base/p5/odds/subsetGuidelines.xsl $H/$ODD \
+    echo "5. make expanded documented ODD"
+    xsltproc --stringparam TEISERVER $TEISERVER $TEIDIR/p5/odds/subsetGuidelines.xsl $H/$ODD \
     | xmllint --format - > $N.doc.xml 
-}
-
-makeXSD()
-{
-    echo "5. simplify expanded form, convert to XSD and then mangle XSD"
-    xsltproc -o $N.temp1.rng $TEIDIR/base/p5/odds/simplifyforxsd.xsl $N.compiled.rng 
-    trang  -o disable-abstract-elements $N.temp1.rng $N.xsd || die " trang fails"
-    cp $N.xsd $N.temp.xsd
-    xsltproc -o $N.xsd $TEIDIR/base/p5/odds/manglexsd.xsl $N.temp.xsd
-    $debug || rm $N.temp.xsd
-    $debug || rm $N.temp1.rng  
-    test -f xml.xsd && perl -p -i -e 's/<xs:import.*//' xml.xsd
 }
 
 die()
@@ -72,7 +69,6 @@ echo "  Usage: Roma [options] schemaspec [output_directory]"
 echo "  options, shown with defaults:"
 echo "  --xsl=$TEIDIR"
 echo "  --teiserver=$TEISERVER"
-echo "  --schema=$S"
 echo "  options, binary switches:"
 echo "  --doc         # create expanded documented ODD"
 echo "  --nodtd       # suppress DTD creation"
@@ -85,9 +81,8 @@ exit 1
 # --------- main routine starts here --------- #
 MYPATH=${0%/*}
 R=/usr/share/xml/tei
-TEISERVER=http://tei.oucs.ox.ac.uk/TEI/Roma/xquery/
-TEIDIR=$R/stylesheet
-S=$R/schema/relaxng/p5/
+TEISERVER=http://tei.oucs.ox.ac.uk/Query/
+TEIDIR=$R/stylesheet/base
 debug=false
 dtd=true
 relax=true
@@ -114,6 +109,7 @@ while test $# -gt 0; do
   shift
 done
 ODD=${1:?"no schemaspec (i.e., ODD file) supplied; for usage syntax issue $0 --help"}
+test -f $ODD || die "file $ODD does not exist"
 N=$(xsltproc $MYPATH/extract-schemaSpec-ident.xsl $1 | head -1)
 N=${N:?"Unable to ascertain ident= of <schemaSpec>"}
 RESULTS=${2:-RomaResults}
@@ -125,18 +121,16 @@ which xmllint || die "you do not have xmllint"
 which xsltproc || die "you do not have xsltproc"
 which trang || die "you do not have trang"
 which perl || die "you do not have perl"
-echo "Schema dir: $S"
-echo "TEI tree: $TEIDIR"
+echo "TEI stylesheet tree: $TEIDIR"
 echo "Results to: $RESULTS"
 test -d $S || die "schema dir $S does not exist"
 test -d $TEIDIR || die "tei dir $TEIDIR does not exist"
 mkdir -p $RESULTS || die "cannot make directory $RESULTS"
 D=`date "+%Y-%m-%d %H:%M:%S.%N"`
-echo "Process $ODD to create $N{.dtd|.xsd|.doc.xml|[compiled].rng|.rnc} in $RESULTS"
+echo "Process $ODD to create $N{.dtd|.xsd|.doc.xml|.rng|.rnc} in $RESULTS"
 echo "========= $D Roma starts, execution:"
 $relax && makeRelax
 $xsd && makeXSD
 $dtd && makeDTD
-$doc && makeDOC
 D=`date "+%Y-%m-%d %H:%M:%S.%N"`
 echo "========= $D Roma ends"
